name: Terraform Plan

on: 
    issue_comment:
        types: [ created ]

jobs:
    plan:
        permissions:
            id-token: write
            contents: read
            pull-requests: write
            statuses: write
        runs-on: ubuntu-latest
        if: github.event.issue.pull_request && contains(github.event.comment.body, '/rezboy_plan')
        steps:
            - name: Plan from Composite Action
              uses: pseudonative/reusable_work_flows/compositAction@main
              with:
                workflow_file: web_app_cicd.yaml
                artifact_name: branch
                artifact_path: BRANCH
                aws_region: us-east-1
                github_token: ${{ secrets.GITHUB_TOKEN }}
                aws_oidc_assume_role: arn:aws:iam::520291287938:role/crom-github-actions-role
              

