name: WebApp CI/CD

on:
    push:
        branches: [ staging-** ]
    pull_request:
        branches: [ staging-** ]

jobs:
    set_the_staging_branch:
      permissions:
          id-token: write
          contents: read
          pull-requests: write
          statuses: write
      runs-on: ubuntu-latest
      steps:
           - name: Plan from Composite Action
             uses: pseudonative/reusable_work_flows/compositBranchAuthAWS@main
             with:
                aws_oidc_assume_role: ${{ secrets.OIDC_ROLE }}
                aws_region: "us-east-1"
                branch: ${{ github.ref_name }}
