name: WebApp CI/CD

on:
    push:
        branches: [ staging-** ]
    pull_request:
        branches: [ staging-** ]


jobs:
    set_the_branch:
      uses: pseudonative/reusable_work_flows/.github/workflows/auth_checkout_initial.yaml@main
      with:
        aws_region: 'us-east-1'
        aws_oidc_assume_role: arn:aws:iam::520291287938:role/crom-github-actions-role
        