name: WebApp CI/CD

on:
    push:
        branches: [ staging-** ]
    pull_request:
        branches: [ staging-** ]

jobs:
    set_the_staging_branch:
      permissions:
          id-token: write
          contents: read
          pull-requests: write
          statuses: write
      uses: pseudonative/reusable_work_flows/.github/workflows/auth_checkout_initial.yaml@main
      with:
        aws_region: 'us-east-1'
        # aws_oidc_assume_role: ${{ secrets.OIDC_ROLE }}
      secrets:
        aws_oidc_assume_role: ${{ secrets.OIDC_ROLE }}